[build]
target = "riscv32imc-esp-espidf"
target-dir = "C:\\esp_b\\epd"

[unstable]
build-std = ["std", "panic_abort"]

# Host build target (Windows with LLVM rust-lld + xwin SDK)
[target.x86_64-pc-windows-msvc]
linker = "C:\\Users\\ZGQ\\.rustup\\toolchains\\esp\\lib\\rustlib\\x86_64-pc-windows-msvc\\bin\\rust-lld.exe"

[target.riscv32imc-esp-espidf]
linker = "ldproxy"
rustflags = ["--cfg", "espidf_time64"]

[env]
ESP_IDF_VERSION = "v5.4"
ESP_IDF_SDKCONFIG_DEFAULTS = "C:\\Users\\ZGQ\\Documents\\antigravity\\epd\\sdkconfig.defaults"
LIB = "C:\\Users\\ZGQ\\.xwin\\crt\\lib\\x64;C:\\Users\\ZGQ\\.xwin\\sdk\\lib\\ucrt\\x64;C:\\Users\\ZGQ\\.xwin\\sdk\\lib\\um\\x64"

